#!/usr/bin/env python3
"""
BIDS Knowledge Base Retriever (JSONL-based).

Drop-in replacement for the original txt/md keyword Retriever. Loads the
structured knowledge base generated by extract_kb.py (knowledge.jsonl,
relationships.jsonl, sources.jsonl) once at construction and serves
repeated queries from an in-memory index.

Public API (unchanged):
    retriever = Retriever("./knowledge")          # data_dir with the JSONL files
    result = retriever.retrieve("What is the task entity?", top_k=2)
    # result is always a formatted string -> passed to the LLM by the Planner

Architecture:
    User Query -> Planner -> Retriever.retrieve(query, top_k) -> LLM

Design notes:
  * Zero external dependencies (Python stdlib only).
  * Loading/parsing, indexing, scoring and formatting are kept in separate
    classes so the token scorer can later be swapped for embeddings.
  * All weights/fields are derived from the ACTUAL schema of the generated
    knowledge base (verified against knowledge.jsonl in this directory).
"""

import json
import logging
import math
import os
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

# Knowledge base file names (relative to data_dir)
KNOWLEDGE_FILE = "knowledge.jsonl"
RELATIONSHIPS_FILE = "relationships.jsonl"
SOURCES_FILE = "sources.jsonl"
REPORT_FILE = "processing_report.json"  # never used as retrieval content

# Fallback messages (stable strings, asserted by tests)
MSG_NO_KB = "Knowledge base file 'knowledge.jsonl' not found in {}."
MSG_EMPTY_KB = "The BIDS knowledge base is empty or could not be loaded."
MSG_EMPTY_QUERY = "An empty query was provided."
MSG_NO_MATCH = 'No relevant BIDS knowledge found for the query: "{}".'

# Queries whose best score falls below this (for a large KB) are treated
# as having no real match, avoiding boilerplate-driven noise for
# out-of-KB terms such as "Funding" or "SourceDatasets". The floor scales
# down with KB size so small knowledge bases still return real matches.
MIN_BEST_SCORE = 6.0


# ====================================================================
# Data model
# ====================================================================


class KnowledgeRecord:
    """
    One record from knowledge.jsonl.

    Maps the real top-level fields of the generated knowledge base:
        id, knowledge_type, title, summary, retrieval_text, scope,
        source, raw_content, bids_version, schema_version, and the
        optional rule fields: requirements, conditions, allowed_values,
        severity, expression, unit.
    """

    __slots__ = (
        "id", "knowledge_type", "title", "summary", "retrieval_text",
        "source", "scope", "raw_content", "bids_version", "schema_version",
        "requirements", "conditions", "allowed_values",
        "severity", "expression", "unit",
    )

    def __init__(self, data: Dict[str, Any]) -> None:
        self.id: str = str(data.get("id", "") or "")
        self.knowledge_type: str = str(data.get("knowledge_type", "unknown"))
        self.title: str = str(data.get("title", "") or "")
        self.summary: str = str(data.get("summary", "") or "")
        self.retrieval_text: str = str(data.get("retrieval_text", "") or "")
        self.source: Dict[str, Any] = data.get("source") or {}
        self.scope: Dict[str, Any] = data.get("scope") or {}
        self.raw_content: Any = data.get("raw_content")
        self.bids_version: str = str(data.get("bids_version", "") or "")
        self.schema_version: str = str(data.get("schema_version", "") or "")
        self.requirements: Any = data.get("requirements")
        self.conditions: Any = data.get("conditions")
        self.allowed_values: Any = data.get("allowed_values")
        self.severity: Any = data.get("severity")
        self.expression: Any = data.get("expression")
        self.unit: Any = data.get("unit")

    # -- searchable representation ------------------------------------

    def build_search_blocks(self) -> List[Tuple[str, str, float]]:
        """
        Build the searchable representation of this record as a list of
        ``(label, text, weight)`` tuples.

        Weights reflect how discriminating each field is:
        * identifiers (id) and scope constraints are the most specific;
        * free-text descriptions are the least specific.
        """
        blocks: List[Tuple[str, str, float]] = []

        def add(label: str, text: Any, weight: float) -> None:
            text = self._normalize(text)
            if text:
                blocks.append((label, text, weight))

        add("id", self.id, 4.0)
        add("title", self.title, 3.0)
        add("scope", self._flatten(self.scope), 3.0)
        add("requirements", self._flatten(self.requirements), 2.5)
        add("allowed_values", self._flatten(self.allowed_values), 2.0)
        add("conditions", self._flatten(self.conditions), 2.0)
        add("summary", self.summary, 1.5)
        add("retrieval", self.retrieval_text, 1.5)
        add("expression", self.expression, 1.5)
        add("severity", self.severity, 1.0)
        add("unit", self.unit, 1.0)
        add("raw_content", json.dumps(self.raw_content, ensure_ascii=False), 0.8)

        return blocks

    def identity_text(self) -> str:
        """Compact text of the most identity-bearing fields (id/title/scope)."""
        return self._normalize(" ".join([
            self.id,
            self.title,
            self._flatten(self.scope),
        ]))

    # -- helpers --------------------------------------------------------

    @staticmethod
    def _normalize(text: Any) -> str:
        """Lowercase and treat '_' as a word separator (BIDS ids use it)."""
        return re.sub(r"[^a-z0-9 ]", " ", str(text or "").lower())

    @classmethod
    def _flatten(cls, value: Any) -> str:
        """Serialize arbitrary JSON values into a flat searchable string."""
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, dict):
            return " ".join(
                f"{k}: {cls._flatten(v)}" for k, v in value.items()
            )
        if isinstance(value, (list, tuple)):
            return " ".join(cls._flatten(v) for v in value)
        return str(value)


class RelationshipEdge:
    """One edge from relationships.jsonl."""

    __slots__ = ("source", "relation", "target", "source_reference", "confidence")

    def __init__(self, data: Dict[str, Any]) -> None:
        self.source: str = str(data.get("source", "") or "")
        self.relation: str = str(data.get("relation", "") or "")
        self.target: str = str(data.get("target", "") or "")
        self.source_reference: str = str(data.get("source_reference", "") or "")
        self.confidence: str = str(data.get("confidence", "explicit"))


# ====================================================================
# Scorer — lightweight token scoring with field-aware weights
# ====================================================================


class Scorer:
    """
    Token-level scorer.

    Rules:
    * Query is tokenized (lowercase, punctuation and '_' are separators,
      stop words removed).
    * A whole-word token match inside a block adds ``2.0 * block_weight``.
    * If a token has no whole-word match anywhere, a prefix match (token
      is a word prefix, length >= 3) adds ``0.5 * block_weight``.
    * Known BIDS identifiers (task, sub, bold, ...) get a flat bonus when
      they appear in the record's identity (id/title/scope).
    * If the whole normalized query appears verbatim in title/summary/
      retrieval_text, a phrase bonus is added.

    Whole-word matching avoids the "every record scores similarly because
    of common words" problem: stop words are excluded and partial/substring
    matches are not rewarded across every record.
    """

    STOPWORDS = frozenset({
        "a", "an", "the", "and", "or", "but", "if", "then", "else",
        "in", "on", "at", "to", "of", "for", "with", "by", "from",
        "is", "are", "was", "were", "be", "been", "being", "it", "its",
        "this", "that", "these", "those", "as", "not", "do", "does",
        "did", "will", "would", "may", "might", "should", "shall",
        "what", "which", "who", "whom", "whose", "why", "how",
        "when", "where", "there", "here", "have", "has", "had",
        "can", "could", "than", "then", "so", "up", "out", "about",
        "into", "within", "without", "under", "over", "between",
        "after", "before", "during", "while", "such", "some", "any",
        "all", "each", "other", "please", "about", "give", "use",
        # Low-information modals / generic JSON-schema vocabulary that
        # would otherwise give near-equal scores to many records.
        "must", "can", "could", "might", "need", "needs", "shall",
        "contains", "containing", "item", "items", "array", "arrays",
        "placeholder", "todo", "value", "values", "list", "lists",
        "string", "boolean", "integer", "number", "numbers",
        "field", "fields", "type", "types", "key", "keys",
        "named", "called", "present", "absent",
        "contain", "include", "includes", "including", "specify",
        "specifies", "specified", "used", "uses", "using", "needed",
        "mean", "means", "make", "makes", "look", "looks",
    })

    # BIDS-specific terms that deserve an identity bonus when matched.
    # '_' is a word separator, so write tokens without underscores.
    BIDS_TERMS = frozenset({
        "sub", "ses", "subject", "session", "task", "acq", "acquisition",
        "run", "space", "desc", "suffix", "extension", "datatype",
        "modality", "bold", "events", "participant", "tsv", "json",
        "nii", "gz", "dataset", "anat", "func", "dwi", "fmap", "perf",
        "eeg", "meg", "ieeg", "pet", "mrs", "micr", "beh", "nirs",
        "motion", "t1w", "t2w", "cbf", "sbref", "echo", "flip", "dir",
        "inv", "hemi", "label", "fieldmap", "channels", "electrodes",
        "physio", "phenotype", "template", "entity", "sourcedata",
        "derivatives", "code", "stimuli", "sessions", "field",
        "metadata", "recommended", "required", "optional",
    })

    # whole-word / prefix matching against normalized (lowercased) text
    _WORD_RE = re.compile(r"\b[a-z0-9]+\b")

    @classmethod
    def tokenize(cls, text: str) -> List[str]:
        return [
            t for t in cls._WORD_RE.findall(KnowledgeRecord._normalize(text))
            if t not in cls.STOPWORDS
        ]

    @classmethod
    def score(
        cls,
        query: str,
        record: KnowledgeRecord,
        blocks: List[Tuple[str, str, float]],
        identity_text: str,
        idf_map: Optional[Dict[str, float]] = None,
    ) -> float:
        if not query or not query.strip():
            return 0.0

        tokens = cls.tokenize(query)
        if not tokens:
            return 0.0

        idf_map = idf_map or {}
        total = 0.0

        # 1. Phrase bonus: whole normalized query appears verbatim.
        norm_query = re.sub(r"\s+", " ", query.lower()).strip()
        phrase_text = " ".join([
            record.title, record.summary, record.retrieval_text,
        ]).lower()
        if norm_query and norm_query in phrase_text:
            total += 5.0

        # 2. Token matches per block.
        for token in tokens:
            variants = cls._match_variants(token)
            idf = idf_map.get(token, 1.0)
            whole_match_any = False
            for _label, text, weight in blocks:
                if any(cls._whole_word(v, text) for v in variants):
                    total += 2.0 * weight * idf
                    whole_match_any = True
            if not whole_match_any and len(token) >= 3:
                for _label, text, weight in blocks:
                    if cls._prefix_word(token, text):
                        total += 0.5 * weight * idf
                        break
            # 3. BIDS identifier bonus (also damped by term rarity).
            if token in cls.BIDS_TERMS and cls._whole_word(token, identity_text):
                total += 3.0 * min(idf, 1.5)

        return total

    @staticmethod
    def _match_variants(token: str) -> Tuple[str, ...]:
        """
        Variants of a query token used for matching, so that common
        BIDS plurals are treated as the same term:
        ``files -> (files, file)``, ``entities -> (entities, entity)``.
        """
        if token.endswith("s") and len(token) >= 4:
            return (token, token[:-1])
        return (token,)

    @staticmethod
    def _whole_word(token: str, text: str) -> bool:
        return re.search(rf"\b{re.escape(token)}\b", text) is not None

    @staticmethod
    def _prefix_word(token: str, text: str) -> bool:
        return re.search(rf"\b{re.escape(token)}[a-z0-9]*", text) is not None


# ====================================================================
# Formatter — record -> LLM-friendly text
# ====================================================================


class Formatter:
    """
    Formats a KnowledgeRecord into readable text for LLM consumption.

    Uses only fields that actually exist in the knowledge base schema.
    """

    RAW_CONTENT_LIMIT = 600

    @classmethod
    def format(
        cls,
        record: KnowledgeRecord,
        index: int,
        source_category: str = "",
    ) -> str:
        parts: List[str] = []
        parts.append(f"=== Knowledge Item {index} ===")
        parts.append(f"ID: {record.id}")
        parts.append(f"Type: {record.knowledge_type}")

        # Provenance (actual schema: source.file / section / key)
        src = record.source
        src_file = src.get("file", "")
        src_section = src.get("section", "")
        src_key = src.get("key", "")
        src_parts = [str(src_file)] if src_file else ["unknown"]
        if src_section:
            src_parts.append(f"section: {src_section}")
        if src_key:
            src_parts.append(f"key: {src_key}")
        parts.append(f"Source: {', '.join(src_parts)}")
        if source_category:
            parts.append(f"Source Category: {source_category}")
        if record.bids_version:
            parts.append(f"BIDS Version: {record.bids_version}")
        if record.schema_version:
            parts.append(f"Schema Version: {record.schema_version}")

        parts.append("")
        if record.title:
            parts.append(f"Title: {record.title}")
        if record.summary:
            parts.append(f"Summary: {record.summary}")
        if record.retrieval_text:
            parts.append(f"Description: {record.retrieval_text}")

        if record.requirements is not None:
            parts.append(f"Requirements: {cls._fmt(record.requirements)}")
        if record.conditions:
            parts.append(f"Conditions: {cls._fmt(record.conditions)}")
        if record.allowed_values:
            parts.append(f"Allowed Values: {cls._fmt(record.allowed_values)}")
        if record.expression:
            parts.append(f"Expression: {record.expression}")
        if record.severity:
            parts.append(f"Severity: {record.severity}")
        if record.unit:
            parts.append(f"Unit: {record.unit}")

        scope_text = cls._fmt_scope(record.scope)
        if scope_text:
            parts.append(f"Scope: {scope_text}")

        if record.raw_content:
            raw_str = json.dumps(record.raw_content, ensure_ascii=False)
            if len(raw_str) > cls.RAW_CONTENT_LIMIT:
                raw_str = raw_str[: cls.RAW_CONTENT_LIMIT] + "..."
            parts.append(f"Raw Content: {raw_str}")

        parts.append("")
        return "\n".join(parts)

    # -- value formatting -----------------------------------------------

    @staticmethod
    def _fmt(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, list):
            return "; ".join(Formatter._fmt(v) for v in value)
        if isinstance(value, dict):
            return ", ".join(
                f"{k}: {Formatter._fmt(v)}" for k, v in value.items()
            )
        return str(value)

    @staticmethod
    def _fmt_scope(scope: Dict[str, Any]) -> str:
        if not scope:
            return ""
        bits: List[str] = []
        for key, value in sorted(scope.items()):
            if isinstance(value, list):
                items = [str(v) for v in value if v not in (None, "")]
                if items:
                    bits.append(f"{key}: {', '.join(items)}")
            elif value not in (None, ""):
                bits.append(f"{key}: {value}")
        return " | ".join(bits)


# ====================================================================
# Retriever — loads the KB once, answers repeated queries
# ====================================================================


class Retriever:
    """
    Loads the JSONL-based BIDS knowledge base and serves keyword queries.

    Parameters
    ----------
    data_dir : str
        Directory containing knowledge.jsonl (and optionally
        relationships.jsonl and sources.jsonl).
    """

    # How many neighbors to consider during relationship expansion.
    MAX_RELATED = 3

    def __init__(self, data_dir: str = "./") -> None:
        self.data_dir = Path(data_dir)

        self.records: List[KnowledgeRecord] = []
        self.blocks: List[List[Tuple[str, str, float]]] = []
        self.identities: List[str] = []
        self.edges: List[RelationshipEdge] = []
        self.source_categories: Dict[str, str] = {}

        # id -> record index (used to resolve relationship endpoints)
        self._index: Dict[str, int] = {}
        # adjacency: record_index -> [(relation, neighbor_index, direction)]
        self._adjacency: Dict[int, List[Tuple[str, int, str]]] = {}
        # term token -> inverse document frequency (computed over the KB)
        self._idf: Dict[str, float] = {}
        # adaptive minimum score for a result to be considered relevant
        self._min_best: float = MIN_BEST_SCORE

        self._load_knowledge()
        self._load_relationships()
        self._load_sources()
        self._build_index()

    # -- Loading --------------------------------------------------------

    def _load_knowledge(self) -> None:
        path = self.data_dir / KNOWLEDGE_FILE
        if not path.exists():
            logger.warning("knowledge.jsonl not found at %s", path)
            return

        loaded, skipped = 0, 0
        try:
            with open(path, "r", encoding="utf-8") as f:
                for line_no, line in enumerate(f, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        if not isinstance(data, dict) or not data.get("id"):
                            raise ValueError("record has no 'id' field")
                        self.records.append(KnowledgeRecord(data))
                        loaded += 1
                    except (json.JSONDecodeError, ValueError) as exc:
                        skipped += 1
                        logger.warning(
                            "Skipping malformed line %d of %s: %s",
                            line_no, path.name, exc,
                        )
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Failed to read %s: %s", path, exc)
            self.records.clear()
            return

        logger.info("Loaded %d records (%d skipped) from %s", loaded, skipped, path.name)

    def _load_relationships(self) -> None:
        path = self.data_dir / RELATIONSHIPS_FILE
        if not path.exists():
            logger.info("relationships.jsonl not found; relationship expansion disabled.")
            return
        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
                if isinstance(data, dict) and data.get("source") and data.get("target"):
                    self.edges.append(RelationshipEdge(data))
            except json.JSONDecodeError:
                logger.warning("Skipping malformed relationship line %d of %s", line_no, path.name)
        logger.info("Loaded %d relationships from %s", len(self.edges), path.name)

    def _load_sources(self) -> None:
        """Load sources.jsonl into a normalized source_path -> category map."""
        path = self.data_dir / SOURCES_FILE
        if not path.exists():
            return
        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
                sp = data.get("source_path", "")
                if sp and data.get("category"):
                    self.source_categories[sp.replace("\\", "/")] = str(data["category"])
            except json.JSONDecodeError:
                logger.warning("Skipping malformed source line %d of %s", line_no, path.name)

    @staticmethod
    def _read_lines(path: Path) -> List[str]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                return [ln.strip() for ln in f if ln.strip()]
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Failed to read %s: %s", path, exc)
            return []

    # -- Indexing -------------------------------------------------------

    def _build_index(self) -> None:
        self.blocks = [r.build_search_blocks() for r in self.records]
        self.identities = [r.identity_text() for r in self.records]
        self._index = {r.id: i for i, r in enumerate(self.records)}

        # Adjacency over edges whose BOTH endpoints resolve to records.
        # (Many relationship nodes are group placeholders that are not
        # themselves knowledge records; those edges are skipped.)
        for edge in self.edges:
            s_idx = self._index.get(edge.source)
            t_idx = self._index.get(edge.target)
            if s_idx is None or t_idx is None:
                continue
            self._adjacency.setdefault(s_idx, []).append((edge.relation, t_idx, "out"))
            self._adjacency.setdefault(t_idx, []).append((edge.relation, s_idx, "in"))

        # IDF map: common boilerplate terms (must/should/field/...) are
        # damped so that specific technical terms dominate the ranking.
        word_re = re.compile(r"[a-z0-9]+")
        df = Counter()
        for blocks in self.blocks:
            seen = set()
            for _label, text, _weight in blocks:
                seen.update(t for t in word_re.findall(text) if t not in Scorer.STOPWORDS)
            df.update(seen)
        n = max(len(self.records), 1)
        self._idf = {
            token: max(0.2, math.log((n + 1) / (count + 1)))
            for token, count in df.items()
        }
        self._min_best = min(MIN_BEST_SCORE, max(0.5, n * 0.005))

        logger.info("Built index: %d records, %d resolvable adjacency entries",
                    len(self.records), sum(len(v) for v in self._adjacency.values()))

    # -- Retrieval ------------------------------------------------------

    def retrieve(self, query: str, top_k: int = 2) -> str:
        """Return the ``top_k`` most relevant knowledge items as a string."""
        if not self.records:
            return MSG_EMPTY_KB if self._knowledge_file_exists() else MSG_NO_KB.format(self.data_dir)

        if not query or not query.strip():
            return MSG_EMPTY_QUERY

        # 1. Score every record.
        scored = self._score_all(query)
        if not scored or scored[0][0] < self._min_best:
            return MSG_NO_MATCH.format(query)

        # 2. Combine base hits with relationship-aware neighbours.
        combined = self._expand_related(query, scored)
        combined.sort(key=lambda x: x[0], reverse=True)

        # 3. Select top_k (deduplicated, stable order).
        selected: List[Tuple[float, int]] = []
        seen: Set[int] = set()
        for score, idx in combined:
            if idx in seen:
                continue
            seen.add(idx)
            selected.append((score, idx))
            if len(selected) >= top_k:
                break

        # 4. Format for the LLM.
        chunks = []
        for rank, (_score, idx) in enumerate(selected, 1):
            record = self.records[idx]
            category = self.source_categories.get(
                str(record.source.get("file", "")).replace("\\", "/"), ""
            )
            chunks.append(Formatter.format(record, rank, category))

        return "\n".join(chunks)

    # -- Scoring internals ----------------------------------------------

    def _score_all(self, query: str) -> List[Tuple[float, int]]:
        scored: List[Tuple[float, int]] = []
        for idx, record in enumerate(self.records):
            s = Scorer.score(
                query, record, self.blocks[idx], self.identities[idx], self._idf
            )
            if s > 0:
                scored.append((s, idx))
        scored.sort(key=lambda x: x[0], reverse=True)
        return scored

    def _expand_related(
        self, query: str, scored: List[Tuple[float, int]]
    ) -> List[Tuple[float, int]]:
        """
        Relationship-aware enrichment.

        For the top results, follow relationships.jsonl edges to neighbours
        and add a small bonus to neighbours that are themselves relevant to
        the query (their own score > 0). This keeps results query-focused:
        an edge alone never pulls in an unrelated record, and the entire
        relationship file is never returned.
        """
        if not self.edges or not scored:
            return list(scored)

        best_score = scored[0][0]
        additions: Dict[int, float] = {}

        for score, idx in scored[: self.MAX_RELATED]:
            for _relation, neighbor_idx, _direction in self._adjacency.get(idx, ()):
                if neighbor_idx in additions:
                    continue
                n_score = Scorer.score(
                    query,
                    self.records[neighbor_idx],
                    self.blocks[neighbor_idx],
                    self.identities[neighbor_idx],
                    self._idf,
                )
                if n_score <= 0:
                    continue
                # Neighbours of the top result get a small nudge.
                bonus = 1.0 if score >= 0.5 * best_score else 0.25
                additions[neighbor_idx] = n_score + bonus

        combined: List[Tuple[float, int]] = list(scored)
        combined.extend((s, i) for i, s in additions.items())
        combined.sort(key=lambda x: x[0], reverse=True)
        return combined

    def _knowledge_file_exists(self) -> bool:
        return (self.data_dir / KNOWLEDGE_FILE).exists()

    # -- Introspection (kept for compatibility) -------------------------

    def get_record_count(self) -> int:
        return len(self.records)

    def get_record_types(self) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for rec in self.records:
            counts[rec.knowledge_type] = counts.get(rec.knowledge_type, 0) + 1
        return counts


# ====================================================================
# Standalone demo
# ====================================================================

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    kb_dir = Path(__file__).parent
    retriever = Retriever(str(kb_dir))

    print(f"Loaded {retriever.get_record_count()} records")
    print(f"Types: {retriever.get_record_types()}")
    print("=" * 70)

    queries = [
        "What is the HEDVersion field used for?",
        # "What is the task entity?",
        # "What are the requirements for a BOLD file?",
        # "Why is sub-01_task-rest_bold.nii.gz valid or invalid?",
        # "What files are required for a BIDS dataset?",
        # "What metadata is required for EEG recordings?",
        # "What is the difference between task and run entities?",
    ]

    for q in queries:
        print(f"\n>>> Query: {q}")
        print("-" * 60)
        print(retriever.retrieve(q, top_k=3))
        print("=" * 70)
